apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: app2
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 1
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
